/** @type {import('tailwindcss').Config} */
const ink = (token) => `rgb(var(${token}) / <alpha-value>)`;

module.exports = {
  content: ['./src/renderer/**/*.{ts,tsx,html}'],
  theme: {
    extend: {
      colors: {
        sidebar: {
          DEFAULT: ink('--ui-sidebar-900'),
          900: ink('--ui-sidebar-900'),
          800: ink('--ui-sidebar-800'),
          700: ink('--ui-sidebar-700'),
          600: ink('--ui-sidebar-600'),
          accent: ink('--ui-sidebar-accent'),
          'accent-hover': ink('--ui-sidebar-accent-hover'),
          hover: ink('--ui-sidebar-hover'),
          active: ink('--ui-sidebar-active'),
        },
        editor: {
          900: ink('--ui-editor-900'),
          850: ink('--ui-editor-850'),
          800: ink('--ui-editor-800'),
          700: ink('--ui-editor-700'),
          600: ink('--ui-editor-600'),
          accent: ink('--ui-editor-accent'),
          'accent-hover': ink('--ui-editor-accent-hover'),
        },
        aichat: {
          900: ink('--ui-aichat-900'),
          800: ink('--ui-aichat-800'),
          700: ink('--ui-aichat-700'),
          600: ink('--ui-aichat-600'),
          accent: ink('--ui-aichat-accent'),
          'accent-hover': ink('--ui-aichat-accent-hover'),
        },
        context: {
          900: ink('--ui-context-900'),
          800: ink('--ui-context-800'),
          700: ink('--ui-context-700'),
          600: ink('--ui-context-600'),
          accent: ink('--ui-context-accent'),
          'accent-hover': ink('--ui-context-accent-hover'),
        },
        inspiration: {
          900: ink('--ui-inspiration-900'),
          800: ink('--ui-inspiration-800'),
          700: ink('--ui-inspiration-700'),
          600: ink('--ui-inspiration-600'),
          accent: ink('--ui-inspiration-accent'),
          'accent-hover': ink('--ui-inspiration-accent-hover'),
        },
        float: {
          900: ink('--ui-float-900'),
          800: ink('--ui-float-800'),
          700: ink('--ui-float-700'),
          600: ink('--ui-float-600'),
          accent: ink('--ui-float-accent'),
          'accent-hover': ink('--ui-float-accent-hover'),
        },
        accent: ink('--ui-accent'),
        'accent-hover': ink('--ui-accent-hover'),
        'accent-blue': ink('--ui-accent-blue'),
        'accent-blue-hover': ink('--ui-accent-blue-hover'),
        'accent-warm': ink('--ui-accent-warm'),
        'accent-warm-hover': ink('--ui-accent-warm-hover'),
        gray: {
          50: ink('--ui-gray-50'),
          100: ink('--ui-gray-100'),
          200: ink('--ui-gray-200'),
          300: ink('--ui-gray-300'),
          400: ink('--ui-gray-400'),
          500: ink('--ui-gray-500'),
          600: ink('--ui-gray-600'),
          700: ink('--ui-gray-700'),
          800: ink('--ui-gray-800'),
          900: ink('--ui-gray-900'),
          950: ink('--ui-gray-950'),
        },
      },
    },
  },
  plugins: [],
};
