import { registerProjectIpc } from './project.ipc';
import { registerChapterIpc } from './chapter.ipc';
import { registerAIIpc } from './ai.ipc';
import { registerOutlineIpc } from './outline.ipc';
import { registerCharacterIpc, registerWorldEntryIpc, registerReferenceLinkIpc, registerSearchIpc } from './entities.ipc';
import { registerImportIpc } from './import.ipc';
import { registerExportIpc } from './export.ipc';
import { registerCryptoIpc } from './crypto.ipc';
import { registerReferenceIpc } from './reference.ipc';
import { registerDatabaseIpc } from './database.ipc';
import { registerForeshadowingIpc } from './foreshadowing.ipc';
import { registerStoryFactsIpc } from './story-facts.ipc';
import { registerNarrativeHooksIpc } from './narrative-hooks.ipc';
import { registerSkillsIpc } from './skills.ipc';
import { registerPlanningIpc } from './planning.ipc';
import { registerObsidianIpc } from './obsidian.ipc';
import { registerConversationIpc } from './conversation.ipc';
import { registerCreativeDecisionIpc } from './creative-decision.ipc';

export function registerAllIpc(): void {
  registerProjectIpc();
  registerChapterIpc();
  registerAIIpc();
  registerOutlineIpc();
  registerCharacterIpc();
  registerWorldEntryIpc();
  registerReferenceLinkIpc();
  registerSearchIpc();
  registerImportIpc();
  registerExportIpc();
  registerCryptoIpc();
  registerReferenceIpc();
  registerDatabaseIpc();
  registerForeshadowingIpc();
  registerStoryFactsIpc();
  registerNarrativeHooksIpc();
  registerSkillsIpc();
  registerPlanningIpc();
  registerObsidianIpc();
  registerConversationIpc();
  registerCreativeDecisionIpc();
}
